### PR TITLE
Enable basic authentication on index page and adding possibility to change the credentials

### PR DESCRIPTION
**Pull request by mliljedahl**
# Basic Authentication
Not really classed as a security feature but at least it adds some kind of protection. Note that the only resource that has basic auth enabled is the index page.

### CODE REVIEW

**Comment by mliljedahl** [comment]
Not sure how active this fork is @munzili? But think the work you have done with this is excellent 👍

**Comment by munzili** [comment]
I like the idea of adding authentication.

As far as I have reviewed your code (I haven't tested it yet), it seems that authentication is only checked on the index page. However, all other API calls are not protected by authentication. This means it is still possible to perform sensitive operations, such as setting a new password or changing configurations, via API calls like /reset, /format, or /saveConfig.

This implementation creates an illusion of security, as users might believe that the ESPAltherma device is properly secured. In reality, however, it remains vulnerable, potentially misleading users into neglecting to configure their Wi-Fi or router settings correctly.

I’m not sure if this solution is robust enough. Perhaps it would be better to add authentication checks to each request or implement a more comprehensive global authentication mechanism?

**Comment by mliljedahl** [comment]
Yes, as I wrote this implementatio is only for the index page and all other api calls are still not behind basic auth. Also having basic auth and over http is mostly to restrict kids and family members to access the web gui. My thought was that if you have someone in your network able to do requests directly to the api, basic auth over http will not stop them and there might be worse things to worrie about. But as you say, for the one that do not know it for sure creates a false security. 

Not sure how much memory is required to create a proper security solution? or if it is worth spending time implementing basic auth over http on the api as well?

**Comment by mliljedahl** [comment]
Perhaps I should share my thoughts about running basic auth over https on an esp32. Usually a weak self signed cert is used to fit in the memory. That creates a pretty easy target for a man-in-the-middle attack for example, since the user do not see a valid cert any ways. But yes, the traffic will be encrypted.

Also basic auth also sends the password repeatedly, for each request which creates a large attack window. And if somehow the device crashes in such a way or sends something over http, the base64 hash is leaked.

So here we have the same issues about false security, is it worth implementing https for this service? I can't tell. But yes, it is way better than http. Guess the decisions that needs to be made is from who are we protecting us from?

This is the long answer for just adding basic auth over http on the index page - to protect the web ui from my kids accidentally doing changes they should not. But on the other hand they first need to change vlan but if they manage to do all this I would be happy :)

**Comment by mliljedahl** [comment]
I now updated the PR to change from Basic Auth to Digest Auth which is a bit better over http. Also enabled it on all requests with a middleware found in a fork from [mathieucarbou](https://github.com/mathieucarbou/ESPAsyncWebServer/tree/main) which is still active.

If I had found a good way of running the web server on HTTPS I would have enabled it. But I'm far from a C++ programmer, perhaps you have any ideas? Or perhaps HTTPS is not required?

**Comment by munzili** [comment]
I can build your code for targeting ESP32, ESP32-C3, and M5StickPlus2, but not for the other devices. Currently, I am considering dropping support for ESP8266 devices like NodeMCU V2, as there are additional issues such as insufficient RAM for current features. Devices like M5StickC, M5Stack-Tough, and M5StickPlus also result in build errors.

**Comment by mliljedahl** [comment]
I will have a look, I did only test esp32 tbh. But removing the support for the others also require some work. Thanks for your reply!

**Comment by mliljedahl** [comment]
I did get m5stick-c to compile by upgrading the m5stick-c lib. The other m5sticks it most likely suffering from things they solved in the m5stick-c lib based on the compiling errors.

I also made an effort trying to get ESP2866 to compile but feel that lack of C++ knowledge stopped me. And About the ESP2866 I found that you are not the only one that thinking about deprecating it; https://github.com/mathieucarbou/ESPAsyncWebServer?tab=readme-ov-file#warning-important-notes-about-future-version-4x

**Review by munzili — APPROVED** [review]
Thanks for your work so far. I did now some researches and tests too. I will approve your PR with your latest changes but modify back the lib changes. I tested how much overload it takes (code size and RAM usage) when adding a simple "request->authenticate(..)" on each available API call. It adds 0.1% firmwire size, so i will just create an Auth Method that is called on each API. So all will be save and no big lib changes needs to be done and all current devices still will be supported

**Comment by mliljedahl** [comment]
Thank you so much! I realised that the readme should be updated as well, and not sure if you want another default user name and password other than admin/admin?

**Pull request merged**
